#!/bin/bash

# 🔍 DIAGNÓSTICO JAVASCRIPT ELIMINANDO CSS
echo "🔍 DIAGNÓSTICO JAVASCRIPT ELIMINANDO CSS"
echo "========================================"

echo "💡 PROBLEMA IDENTIFICADO:"
echo "El CSS carga (visible por instante) pero JavaScript lo elimina después"
echo ""

echo "🔧 ACCIONES INMEDIATAS EN DEVTOOLS:"
echo "=================================="
echo ""
echo "1. 🌐 Abre: https://crm.arifamilyassets.com"
echo "2. 🔧 F12 → Network tab ANTES de cargar"
echo "3. 🔄 Reload (F5)"
echo "4. 🔍 Busca archivos CSS cargados"
echo "5. ✅ ¿CSS carga con HTTP 200?"
echo ""
echo "Si CSS carga pero desaparece:"
echo "----------------------------"
echo ""
echo "6. 🔧 F12 → Console"
echo "7. 📝 Pega este código para debug:"
echo ""
echo "// DETECTAR QUÉ ESTÁ ELIMINANDO EL CSS"
echo "const observer = new MutationObserver(mutations => {"
echo "  mutations.forEach(mutation => {"
echo "    if (mutation.type === 'childList') {"
echo "      mutation.removedNodes.forEach(node => {"
echo "        if (node.tagName === 'LINK' && node.rel === 'stylesheet') {"
echo "          console.error('🚨 CSS LINK ELIMINADO:', node.href);"
echo "          console.trace('Stack trace del culpable:');"
echo "        }"
echo "        if (node.tagName === 'STYLE') {"
echo "          console.error('🚨 STYLE TAG ELIMINADO:', node.textContent.substring(0, 100));"
echo "          console.trace('Stack trace del culpable:');"
echo "        }"
echo "      });"
echo "    }"
echo "    if (mutation.type === 'attributes' && mutation.attributeName === 'class') {"
echo "      console.log('🔄 CLASE CAMBIADA:', mutation.target, 'Nueva:', mutation.target.className);"
echo "    }"
echo "  });"
echo "});"
echo ""
echo "observer.observe(document, {"
echo "  childList: true,"
echo "  subtree: true,"
echo "  attributes: true,"
echo "  attributeFilter: ['class', 'style']"
echo "});"
echo ""
echo "console.log('🕵️ Observer activado - detectará cambios CSS');"
echo ""
echo "8. 🔄 Reload nuevamente"
echo "9. 📊 Ver qué aparece en Console"
echo ""
echo "ALTERNATIVA RÁPIDA:"
echo "=================="
echo "En Console, también ejecutar:"
echo ""
echo "// VERIFICAR SI CSS ESTÁ CARGADO"
echo "console.log('CSS Links:', document.querySelectorAll('link[rel=\"stylesheet\"]'));"
echo "console.log('Style Tags:', document.querySelectorAll('style'));"
echo ""
echo "// VERIFICAR COMPUTADO DE ELEMENTO FLEX"
echo "const flexEl = document.querySelector('.flex');"
echo "if (flexEl) {"
echo "  console.log('Elemento .flex encontrado:', flexEl);"
echo "  console.log('Computed display:', getComputedStyle(flexEl).display);"
echo "  console.log('Todas las clases:', flexEl.className);"
echo "} else {"
echo "  console.log('❌ No hay elementos con clase .flex');"
echo "}"